# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UX Stash
email: hello@uxstash.io
description: > # this means to ignore newlines until "baseurl:"
  UX links and goodies
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uxstash.io/" # the base hostname & protocol for your site
twitter_username: ux_stash
github_username:  uxstash

# Build settings
markdown: kramdown
