# Site settings
title: UX Stash
email: hello@uxstash.io
description: > # this means to ignore newlines until "baseurl:"
  User Experience curated design collections
url: "http://uxstash.io/" # the base hostname & protocol for your site
twitter_username: ux_stash
github_username:  uxstash

# Build settings
markdown: kramdown

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-76489278-1

gems:
  - jekyll-assets
  - jekyll-sitemap

name: UX Stash

permalink: pretty
